### ISSUE TITLE
UI could use some work

### ISSUE THREAD

**Issue by ccorrodi** [scg-unibe-ch/ese2016-team5#7]
The UI still feels a bit cheap. Can you improve it? For example, it doesn't really work on smaller screens/windows. When I open it on my phone, I have to scroll like crazy.

**Comment by sserena** [comment]
Claudio, 

 

Thanks for your feedback; I think it’s all very appropriate. This said, one question: Can you remember when I asked you whether or not you expect the page to be responsive (which is exactly what designing for smaller screens entails)? It was right when the first iteration of our design was completed, a number of weeks ago. According to our recollection, you said that this is not necessary, it would be too much work. And yes, particularly with the jumble of code that particularly the HTML/CSS is, it would be a bit of an effort to do it properly. Also, with time being at a premium at this point, maybe it’s justifiable to drop this request? What do you think?

 

Thanks!

 

Stefan

 

 

Von: Claudio Corrodi [mailto:notifications@github.com] 
Gesendet: Sonntag, 4. Dezember 2016 17:52
An: scg-unibe-ch/ese2016-team5 <ese2016-team5@noreply.github.com>
Betreff: [scg-unibe-ch/ese2016-team5] UI could use some work (#7)

 

The UI still feels a bit cheap. Can you improve it? For example, it doesn't really work on smaller screens/windows. When I open it on my phone, I have to scroll like crazy.

**Comment by ccorrodi** [comment]
Ah yes, I remember. It’s ok to not have a responsive design, sorry about the confusion. You can close the issue (but of course if you want to do something different on the UI this would be welcome, especially with regard to the showcase in 1.5 weeks).
